### ISSUE TITLE
Website v1.0 Roadmap

### ISSUE THREAD

**Issue by austinEng** [GraceCovenantChurch/gccweb#18]
- [ ] Admin interface
    - [ ] Editable main announcements #20 
         - Title
         - Text
         - Link #11 
         - Image
    - [ ] Editable small announcements
         - Text
    - [ ] Editable memory verses
         - Reference
         - Verse
         - Image
- [ ] Client
    - [ ] Discuss this with staff. Separation of mainline / UC content. Should we just have one site with different announcement sections? or two separate sites on different subdomains?
    - [ ] Minimal design changes for release #23
