### ISSUE TITLE
Website v1 Roadmap

### ISSUE THREAD

**Issue by austinEng** [GraceCovenantChurch/gccweb#70]
- [ ] Public website design #23 
- [ ] Admin panel design #29 
- [ ] Static pages
    - [ ] Home page #41 
    - [x] Welcome page
    - [ ] About page
    - [ ] Family group page #44
    - [ ] Ministries page
    - [ ] Giving page
    - [ ] Multimedia page
    - [ ] Events page
- [ ] Admin Panel
    - [ ] Image Uploads #71
    - [ ] Sermon Uploads
