### ISSUE TITLE
AWS Roadmap

### ISSUE THREAD

**Issue by austinEng** [GraceCovenantChurch/gccweb#74]
- [ ] S3 Buckets
    - [ ] Both dev and prod buckets
    - [ ] Sermon uploads
    - [ ] Image uploads
- [ ] Staging environment for testing
- [ ] Separate EC2 instances for admin/public
- [ ] EC2 instance for all application DBs
    - one for dev, one for prod
